repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff # Runs ruff linter (replaces flake8)
        args: [--fix, --exit-non-zero-on-fix] # --fix for fixing errors
      - id: ruff-format
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.4.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg]
